export const DELETE_TECHNICIAN = "DELETE_TECHNICIAN";
export const ADD_TECHNICIAN = "ADD_TECHNICIAN";
export const EDIT_TECHNICIAN = "EDIT_TECHNICIAN";

export const DELETE_BUILDING = "DELETE_BUILDING";
export const ADD_BUILDING = "ADD_BUILDING";
export const EDIT_BUILDING = "EDIT_BUILDING";

export const GET_BOILERTYPES_FETCHING = "GET_BOILERTYPES_FETCHING";
export const GET_BOILERTYPES_FULFILLED = "GET_BOILERTYPES_FULFILLED";
export const GET_BOILERTYPES_REJECTED = "GET_BOILERTYPES_REJECTED";

export const ADD_BOILERTYPE_FETCHING = "ADD_BOILERTYPE_FETCHING";
export const ADD_BOILERTYPE_FULFILLED = "ADD_BOILERTYPE_FULFILLED";
export const ADD_BOILERTYPE_REJECTED = "ADD_BOILERTYPE_REJECTED";

export const EDIT_BOILERTYPE_FETCHING = "EDIT_BOILERTYPE_FETCHING";
export const EDIT_BOILERTYPE_FULFILLED = "EDIT_BOILERTYPE_FULFILLED";
export const EDIT_BOILERTYPE_REJECTED = "EDIT_BOILERTYPE_REJECTED";

export const DELETE_BOILERTYPE_FETCHING = "DELETE_BOILERTYPE_FETCHING";
export const DELETE_BOILERTYPE_FULFILLED = "DELETE_BOILERTYPE_FULFILLED";
export const DELETE_BOILERTYPE_REJECTED = "DELETE_BOILERTYPE_REJECTED";