export const DELETE_TECHNICIAN = "DELETE_TECHNICIAN";
export const ADD_TECHNICIAN = "ADD_TECHNICIAN";
export const EDIT_TECHNICIAN = "EDIT_TECHNICIAN";

export const DELETE_BUILDING = "DELETE_BUILDING";
export const ADD_BUILDING = "ADD_BUILDING";
export const EDIT_BUILDING = "EDIT_BUILDING";

export const DELETE_COMPANY = "DELETE_COMPANY";
export const ADD_COMPANY = "ADD_COMPANY";
export const EDIT_COMPANY = "EDIT_COMPANY";