export const DELETE_TECHNICIAN = "DELETE_TECHNICIAN";
export const ADD_TECHNICIAN = "ADD_TECHNICIAN";
export const EDIT_TECHNICIAN = "EDIT_TECHNICIAN";

export const DELETE_BUILDING = "DELETE_BUILDING";
export const ADD_BUILDING = "ADD_BUILDING";
export const EDIT_BUILDING = "EDIT_BUILDING";

export const DELETE_BOILERTYPE = "DELETE_BOILERTYPE";
export const ADD_BOILERTYPE = "ADD_BOILERTYPE";
export const EDIT_BOILERTYPE = "EDIT_BOILERTYPE";