const modalTypes = {
  ADD_EDIT_BUILDING: "ADD_EDIT_BUILDING",
  DELETE_BUILDING: "DELETE_BUILDING",
  ADD_EDIT_TECHNICIAN: "ADD_EDIT_TECHNICIAN",
  DELETE_TECHNICIAN: "DELETE_TECHNICIAN",
  ADD_EDIT_COMPANY: "ADD_EDIT_COMPANY",
  DELETE_COMPANY: "DELETE_COMPANY",
  ADD_EDIT_BOILER: "ADD_EDIT_BOILER",
  DELETE_BOILER: "DELETE_BOILER",
};

export default modalTypes;
